USE [master]
GO

/****** Object:  Database [ShareMate]    Script Date: 12.07.2020 12:40:21 ******/
CREATE DATABASE [ShareMate]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ShareMate', FILENAME = N'D:\SQLExpress\MSSQL14.SQLEXPRESS\MSSQL\DATA\ShareMate.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ShareMate_log', FILENAME = N'D:\SQLExpress\MSSQL14.SQLEXPRESS\MSSQL\DATA\ShareMate_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ShareMate].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ShareMate] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ShareMate] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ShareMate] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ShareMate] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ShareMate] SET ARITHABORT OFF 
GO

ALTER DATABASE [ShareMate] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ShareMate] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ShareMate] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ShareMate] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ShareMate] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ShareMate] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ShareMate] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ShareMate] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ShareMate] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ShareMate] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ShareMate] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ShareMate] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ShareMate] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ShareMate] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ShareMate] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ShareMate] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ShareMate] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ShareMate] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ShareMate] SET  MULTI_USER 
GO

ALTER DATABASE [ShareMate] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ShareMate] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ShareMate] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ShareMate] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ShareMate] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ShareMate] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ShareMate] SET  READ_WRITE 
GO

